CREATE PROCEDURE `deleteUser`(
    in puuid varchar(36)
)
BEGIN DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN SHOW ERRORS
LIMIT
    1;

ROLLBACK;

END;

DECLARE EXIT HANDLER FOR SQLWARNING BEGIN SHOW WARNINGS
LIMIT
    1;

ROLLBACK;

END;

START TRANSACTION;

DELETE FROM PAS_PersonPsychologist WHERE uuid=puuid;
DELETE FROM PAS_PersonUser WHERE uuid=puuid;
DELETE FROM PAS_Person WHERE uuid=puuid;
COMMIT;

END